### ISSUE TITLE
Unable to run in Ubuntu 24.04

### ISSUE THREAD

**Issue by josdem** [josdem/jmetadata#12]
**Steps to reproduce**
- Download Jmetadata-Linux.zip from [here](https://github.com/josdem/jmetadata/wiki/Downloads)
- Unzip downloaded file
- Execute the shell: `JMetadata.sh`

**Expected Result**
Application running

**Actual Result**
An exception is thrown
```bash
Error creating bean with name 'completeController' defined in URL [jar:file:/home/josdem/Programs/Jmetadata/System/Jar/jmetadata-0.0.1-SNAPSHOT.jar!/org/jas/controller/CompleteController.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.jas.controller.CompleteController]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:965)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:911)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:580)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at org.jas.helper.ApplicationContextSingleton.getApplicationContext(ApplicationContextSingleton.java:219)
	at org.jas.Launcher.main(Launcher.java:242)
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.jas.controller.CompleteController]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
```

**References**
- https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception

**Comment by josdem** [comment]
Package updated: https://github.com/josdem/jmetadata/wiki/Jmetadata-linux.zip
